apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xvaliceks-wac-project-content
spec:
  microFrontend: polyfea-md-shell
  element: reservation-manager
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^/fea/xvaliceks-ui(/.*)?$"