apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/polyfea/manifests//controller
  - https://github.com/polyfea/manifests//md-shell

patches:
  - path: ./patches/service.yaml