apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/polyfea/manifests//controller
  - https://github.com/polyfea/manifests//md-shell
  - http-route.yaml           
  - http-route-wac-school.yaml

patches:
  - path: ./patches/service.yaml