apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"wac-project-api","namespace":"wac-hospital"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"wac-project-api"}},"template":{"metadata":{"labels":{"app":"wac-project-api"}},"spec":{"containers":[{"env":[{"name":"AMBULANCE_API_MONGODB_HOST","value":"mongodb.wac-hospital-system.svc.cluster.local"}],"image":"xvaliceks/wac-project-api:latest","imagePullPolicy":"Always","name":"wac-project-api","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"0.3","memory":"320M"},"requests":{"cpu":"0.1","memory":"32M"}}}]}}}}
  creationTimestamp: "2025-06-17T00:45:38Z"
  generation: 11
  name: wac-project-api
  namespace: wac-hospital
  resourceVersion: "166652641"
  uid: 498a3f6b-7473-447c-bf0a-f0d96d52e00d
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wac-project-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-17T05:09:32+02:00"
      creationTimestamp: null
      labels:
        app: wac-project-api
    spec:
      containers:
      - env:
        - name: AMBULANCE_API_MONGODB_HOST
          value: mongodb.wac-hospital-system.svc.cluster.local
        image: xvaliceks/wac-project-api:latest
        imagePullPolicy: Always
        name: wac-project-api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 320M
          requests:
            cpu: 100m
            memory: 32M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-06-17T03:03:17Z"
    lastUpdateTime: "2025-06-17T03:03:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-17T00:45:39Z"
    lastUpdateTime: "2025-06-17T03:09:37Z"
    message: ReplicaSet "wac-project-api-7c74ff4f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
