apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: wac-gitops
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/SimonValicek/wac-gitops
