apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-gitops

labels:
- pairs:
    app.kubernetes.io/part-of: wac-gitops

resources:
  - git-repository.yaml
  - prepare.kustomization.yaml
  - install.kustomization.yaml
  - cd.kustomization.yaml
