apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wac-project
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: wac-project
  filterTags:
    pattern: "master.*"  # filters tags starting with "main"
  policy:
    alphabetical:
      order: asc
