apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wac-school
  namespace: wac-gitops
spec:
  imageRepositoryRef:
    name: wac-school
  filterTags:
    pattern: ".*"
  policy:
    alphabetical:
      order: asc
