apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

patchesStrategicMerge:
  - patch-mongo-host.yaml

namespace: wac-hospital

images:
  - name: xvaliceks/wac-project-api
    newTag: v1.1.5