apiVersion: apps/v1
kind: Deployment
metadata:
  name: xvaliceks-wac-school-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: xvaliceks-wac-school-label
  template:
    metadata:
      labels:
        pod: xvaliceks-wac-school-label
    spec:
      containers:
      - name: wac-school-container
        image: xvaliceks/wac-school
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "32M"
            cpu: "0.1"
          limits:
            memory: "320M"
            cpu: "0.3"
      imagePullSecrets:
      - name: dockerhub-creds