apiVersion: v1
kind: Service
metadata:
  name: xvaliceks-wac-school
  namespace: wac-hospital
spec:
  selector:
    pod: xvaliceks-wac-school-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http