apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

resources:
- ../../../apps/wac-project
- ../../../apps/wac-project-api

images:
  - name: xvaliceks/wac-project
    newTag: v1.0.2
  - name: xvaliceks/wac-project-api
    newTag: v1.1.5
