apiVersion: v1
kind: Service
metadata:
  name: polyfea-controller
  namespace: polyfea
spec:
  ports:
    - name: webserver
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30331
  type: NodePort